#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Export a directory of invoice images to a reviewable finance OCR batch."""

import csv
import json
import os
import shutil
import sys
from datetime import datetime

from invoice_ocr import parse_one


def unique_path(folder, filename):
    stem, ext = os.path.splitext(filename)
    target = os.path.join(folder, filename)
    index = 2
    while os.path.exists(target):
        target = os.path.join(folder, f"{stem}_{index}{ext}")
        index += 1
    return target


def main():
    if len(sys.argv) not in (3, 4):
        raise SystemExit("用法：export_invoice_batch.py <发票目录> <输出目录> [--reset-output]")
    source_dir, output_dir = sys.argv[1:3]
    reset_output = len(sys.argv) == 4 and sys.argv[3] == "--reset-output"
    stamp = datetime.now().strftime("%Y-%m-%d")
    os.makedirs(output_dir, exist_ok=True)
    archive_dir = os.path.join(output_dir, "全部识别发票")
    if reset_output:
        # These two folders are generated by the previous exporter version;
        # source invoice files stay untouched in input/.
        for legacy_dir in (os.path.join(output_dir, "OCR识别发票"), os.path.join(output_dir, "待人工核对"), archive_dir):
            if os.path.isdir(legacy_dir):
                shutil.rmtree(legacy_dir)
    os.makedirs(archive_dir, exist_ok=True)

    records, failures = [], []
    for filename in sorted(os.listdir(source_dir)):
        if not filename.lower().endswith((".png", ".jpg", ".jpeg")):
            continue
        source = os.path.join(source_dir, filename)
        try:
            record, error = parse_one(source)
        except Exception as exc:  # one problematic image must not stop the batch
            record, error = None, f"OCR异常：{exc}"
        if not record:
            record = {
                "原文件": filename, "原路径": source, "发票号码": "〔待确认〕",
                "开票日期": "〔待确认〕", "购买方": "〔待确认〕", "销售方": "〔待确认〕",
                "金额": "〔待确认〕", "方向": "待确认", "建议文件名": f"待确认_{filename}",
                "待确认字段": error or "OCR异常",
            }
            failures.append({"原文件": filename, "原路径": source, "原因": record["待确认字段"]})
        ext = os.path.splitext(filename)[1].lower()
        date_part = record["开票日期"].replace("-", "") if record["开票日期"].count("-") == 2 else "00000000"
        number_part = record["发票号码"] if record["发票号码"].isdigit() else os.path.splitext(filename)[0][:12]
        amount_part = record["金额"].replace("-", "红冲") if record["金额"] != "〔待确认〕" else "待确认"
        target = unique_path(archive_dir, f"{date_part}-{number_part}-{amount_part}{ext}")
        shutil.copy2(source, target)
        record["归档文件"] = os.path.relpath(target, output_dir)
        record["方向"] = "进项（按批次目录）" if "进账" in os.path.basename(source_dir) else record["方向"]
        record["核对状态"] = "完整识别" if not record.get("待确认字段") else "部分识别—待人工核验"
        record["核对备注"] = "购销方为 OCR 候选字段；请以电子发票原件及税务口径复核。"
        records.append(record)

    payload = {
        "批次": os.path.basename(source_dir),
        "生成时间": datetime.now().isoformat(timespec="seconds"),
        "识别记录": len(records),
        "完整识别": sum(not x.get("待确认字段") for x in records),
        "部分识别": sum(bool(x.get("待确认字段")) for x in records),
        "records": records,
        "failures": failures,
    }
    with open(os.path.join(output_dir, f"{stamp}_进账发票0815_发票识别结果.json"), "w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)

    csv_rows = []
    for index, record in enumerate(records, start=1):
        csv_rows.append([
            index, record["原文件"], record["发票号码"], record["开票日期"],
            record["购买方"], record["销售方"], record["金额"], record["方向"], record.get("待确认字段", ""),
            record["核对状态"], record["归档文件"], record["核对备注"],
        ])
    headers = ["序号", "原文件", "发票号码", "开票日期", "购买方（OCR候选）", "销售方（OCR候选）", "价税合计（元）", "方向", "待确认字段", "核对状态", "归档文件", "核对备注"]
    with open(os.path.join(output_dir, f"{stamp}_进账发票0815_发票识别明细.csv"), "w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(headers)
        writer.writerows(csv_rows)

    pending = [x for x in records if x.get("待确认字段")]
    with open(os.path.join(output_dir, f"{stamp}_进账发票0815_待确认字段清单.csv"), "w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=["原文件", "待确认字段", "归档文件"], extrasaction="ignore")
        writer.writeheader()
        writer.writerows(pending)

    total_amount = sum(float(record["金额"]) for record in records if record["金额"] != "〔待确认〕")
    report = [
        "# 进账发票 0815 智能识别结果",
        "",
        f"- 输入批次：`{source_dir}`",
        f"- 识别时间：{payload['生成时间']}",
        f"- 已形成 OCR 记录：{len(records)} 张（覆盖全部输入图片）",
        f"- 完整识别：{payload['完整识别']} 张；部分识别：{payload['部分识别']} 张",
        f"- 已提取金额的 OCR 记录价税合计：¥{total_amount:,.2f}",
        "",
        "## 核验说明",
        "",
        "- 本批次为 OCR 工作底稿，发票号码、日期、金额及购销方均须以电子发票原件为准。",
        "- 购买方、销售方保留为 OCR 候选字段，未自动写入正式财税台账。",
        "- `全部识别发票/` 保存全部 95 张按“日期-发票号码-价税合计”命名的副本；原始输入文件未作修改。",
        "- 部分识别图片不会被剔除，缺失字段统一列入《待确认字段清单》。",
    ]
    with open(os.path.join(output_dir, f"{stamp}_进账发票0815_识别说明.md"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(report) + "\n")

    print(json.dumps({"output_dir": output_dir, "records": len(records), "partial": len(pending), "exceptions": len(failures)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
