export const IPC = {
  configGet: 'config:get',
  configPickDataDir: 'config:pick-data-dir',
  configSetActiveProvider: 'config:set-active-provider',
  configSetProviderConfig: 'config:set-provider-config',

  configAddCompany: 'config:add-company',
  configRemoveCompany: 'config:remove-company',
  configSetCompanyDataDir: 'config:set-company-data-dir',
  configSetActiveCompany: 'config:set-active-company',
  configRepairDataDir: 'config:repair-data-dir',
  identityResetAllMembers: 'identity:reset-all-members',
  financeProcessInvoices: 'finance:process-invoices',
  intelKeywordSuggestions: 'intel:keyword-suggestions',
  brandListMatters: 'brand:list-matters',
  brandSetMatter: 'brand:set-matter',
  appVersion: 'app:version',
  envCheck: 'env:check',
  envInstall: 'env:install',

  agentsList: 'agents:list',
  agentRun: 'agent:run',
  agentCancel: 'agent:cancel',
  agentStreamEvent: 'agent:stream-event',

  dialogPickFiles: 'dialog:pick-files',
  shellShowItemInFolder: 'shell:show-item-in-folder',
  shellSaveAsCopy: 'shell:save-as-copy',

  uploadGeneric: 'upload:generic',
  uploadBiddingProject: 'upload:bidding-project',
  uploadBiddingMaterial: 'upload:bidding-material',
  uploadLegalPending: 'upload:legal-pending',
  uploadOperationTheme: 'upload:operation-theme',
  operationApplyImageNames: 'operation:apply-image-names',
  salesGenPdfQuoteList: 'sales:gen-pdf-quote-list',
  salesExtractPdfCatalog: 'sales:extract-pdf-catalog',
  salesApplyCatalogPairing: 'sales:apply-catalog-pairing',
  salesCatalogProgress: 'sales:catalog-progress',
  salesExportZcy: 'sales:export-zcy',
  operationUploadTemplate: 'operation:upload-template',
  operationListTemplates: 'operation:list-templates',
  operationRecentArticles: 'operation:recent-articles',

  outputsScan: 'outputs:scan',

  biddingListProjects: 'bidding:list-projects',
  biddingMaterialCounts: 'bidding:material-counts',
  biddingSaveCard: 'bidding:save-card',
  biddingExportLedger: 'bidding:export-ledger',
  uploadBiddingClarification: 'upload:bidding-clarification',
  uploadBiddingTenderFile: 'upload:bidding-tender-file',
  biddingListCandidates: 'bidding:list-candidates',
  biddingConfirmCandidate: 'bidding:confirm-candidate',
  biddingIgnoreCandidate: 'bidding:ignore-candidate',
  biddingDownloadTender: 'bidding:download-tender',
  biddingProbeTender: 'bidding:probe-tender',
  biddingDeleteProject: 'bidding:delete-project',
  intelListReports: 'intel:list-reports',
  intelPurgeStale: 'intel:purge-stale',
  intelFetchNow: 'intel:fetch-now',
  intelSaveReportToSolution: 'intel:save-report-to-solution',
  intelFetchReports: 'intel:fetch-reports',
  intelGetKeywords: 'intel:get-keywords',
  intelSetKeywords: 'intel:set-keywords',

  legalListDocs: 'legal:list-docs',
  legalMarkReviewed: 'legal:mark-reviewed',
  legalListTemplates: 'legal:list-templates',
  legalUploadTemplate: 'legal:upload-template',
  legalGenerateRedline: 'legal:generate-redline',

  docgenExportMarkdownFile: 'docgen:export-markdown-file',
  docgenExportBiddingTriSplit: 'docgen:export-bidding-tri-split',
  docgenExportMarkdownPptx: 'docgen:export-markdown-pptx',

  gzhRunStyle: 'gzh:run-style',
  gzhGenerateCover: 'gzh:generate-cover',
  updateCheck: 'update:check',
  updateDownload: 'update:download',
  updateGetTokenSet: 'update:get-token-set',
  updateSetToken: 'update:set-token',
  shellOpenPath: 'shell:open-path',

  identityList: 'identity:list',
  identityAdd: 'identity:add',
  identityRemove: 'identity:remove',
  identityVerifyPin: 'identity:verify-pin',
  identitySetRole: 'identity:set-role',
  identityNotifyLogin: 'identity:notify-login',

  syncStatus: 'sync:status',
  syncNow: 'sync:now',
  syncLastAt: 'sync:last-at',

  salesListProducts: 'sales:list-products',
  salesSaveProduct: 'sales:save-product',
  salesRemoveProduct: 'sales:remove-product',
  salesSetProductImage: 'sales:set-product-image',
  salesUploadSupplierDoc: 'sales:upload-supplier-doc',
  salesImportExcel: 'sales:import-excel',
  salesExportQuoteImages: 'sales:export-quote-images',
  salesGenerateQuoteXlsx: 'sales:generate-quote-xlsx',
  salesListTemplates: 'sales:list-templates',
  salesUploadTemplate: 'sales:upload-template',
  salesListCustomers: 'sales:list-customers',
  salesSaveCustomer: 'sales:save-customer',
  salesRemoveCustomer: 'sales:remove-customer',
  salesAddFollowUp: 'sales:add-follow-up',
  salesLinkCustomerFile: 'sales:link-customer-file',
  salesUnlinkCustomerFile: 'sales:unlink-customer-file',
  salesResolveLinkedPath: 'sales:resolve-linked-path',

  solutionListFiles: 'solution:list-files',
  solutionUpload: 'solution:upload',
  solutionRemoveFile: 'solution:remove-file',

  financeOverview: 'finance:overview',
  financeToggleTask: 'finance:toggle-task',
  financeSaveEmployees: 'finance:save-employees',
  financeUploadReceipt: 'finance:upload-receipt',
  financeListReceipts: 'finance:list-receipts',

  opsListPolicyDocs: 'ops:list-policy-docs',
  opsSetPolicyDocState: 'ops:set-policy-doc-state',
  opsListGovernanceDocs: 'ops:list-governance-docs',
  opsSetGovernanceState: 'ops:set-governance-state',

  identityChangePin: 'identity:change-pin',
  identityResetPin: 'identity:reset-pin',
  identitySetAgents: 'identity:set-agents',
  configInitDataDir: 'config:init-data-dir'
} as const
